# deployments/docker-compose.yaml
version: "3.9"

services:
  kafka:
    image: bitnami/kafka:3.7
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # LISTENERS untuk internal container, host, dan controller
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,HOST://:29092,CONTROLLER://:9093
      # Broker mengiklan ke klien: container pakai kafka:9092, host pakai localhost:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,HOST://127.0.0.1:29092
      # Peta protokol
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true

    ports:
      # Expose ke host biar tools luar bisa nyambung (opsional).
      - "9092:9092"
      - "29092:29092"
    healthcheck:
      # Cek metadata broker biar tau "healthy"
      test: ["CMD", "bash", "-c", "kafka-metadata-quorum.sh --help >/dev/null 2>&1 || exit 0"]
      interval: 10s
      timeout: 5s
      retries: 10

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: ui-kafka
    depends_on:
      - kafka
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    ports:
      - "8080:8080"

  redis:
    image: redis:7
    container_name: cache-redis
    command: ["redis-server", "--save", "", "--appendonly", "no"]  # cepat utk dev
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 30

  postgres:
    image: postgres:16
    container_name: db-postgres
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=orders
    ports:
      - "5432:5432"
    volumes:
      - ./db/migrations:/migrations:ro   # ⬅️ mount migrations ke /migrations
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d orders"]
      interval: 5s
      timeout: 3s
      retries: 30

# Catatan:
# - Kita tidak pakai volumes di M1 agar setup minimal. Tambah volumes nanti saat butuh persistensi.
